site_name: ADORe Documentation
repo_url: https://github.com/eclipse-adore/adore

nav:
  - Home: index.md
  - Overview:
      - What is ADORe?: technical_reference_manual/about_adore.md
      - Quick start: technical_reference_manual/quick_start.md
      - Publications: technical_reference_manual/publications.md
      - Contact: technical_reference_manual/contact.md

  - Getting started:
      - Getting started guide: technical_reference_manual/getting_started/getting_started.md
      - System requirements: technical_reference_manual/getting_started/system_requirements.md
      - Prerequisites: technical_reference_manual/getting_started/prerequisites.md
      - Installing Docker: technical_reference_manual/getting_started/installing_docker.md
      - Run your first scenario: technical_reference_manual/getting_started/running_your_first_scenario.md

  - Code reference:
      - Overview: generated/README.md
      - Scenarios:
          - ADORe scenarios: generated/adore_scenarios/README.md

      - Libraries:
          - adore_controllers: generated/adore_libraries/adore_controllers/README.md
          - adore_dynamics: generated/adore_libraries/adore_dynamics/README.md
          - adore_map: generated/adore_libraries/adore_map/README.md
          - adore_math: generated/adore_libraries/adore_math/README.md
          - adore_planning: generated/adore_libraries/adore_planning/README.md

      - Nodes:
          - decision_maker: generated/adore_ros2_nodes/decision_maker/README.md
          - decision_maker_infrastructure: generated/adore_ros2_nodes/decision_maker_infrastructure/README.md
          - mission_control: generated/adore_ros2_nodes/mission_control/README.md
          - simulated_remote_operator: generated/adore_ros2_nodes/simulated_remote_operator/README.md
          - simulated_vehicle: generated/adore_ros2_nodes/simulated_vehicle/README.md
          - trajectory_tracker: generated/adore_ros2_nodes/trajectory_tracker/README.md
          - visualizer: generated/adore_ros2_nodes/visualizer/README.md

      - Interfaces:
          - CARLA bridge: generated/adore_interfaces/carla_bridge/README.md
          - SUMO bridge: generated/adore_interfaces/sumo_bridge/README.md

      - Conversions:
          - adore_dynamics_conversions: generated/adore_ros2_conversions/adore_dynamics_conversions/README.md
          - adore_map_conversions: generated/adore_ros2_conversions/adore_map_conversions/README.md
          - adore_math_conversions: generated/adore_ros2_conversions/adore_math_conversions/README.md

      - ROS 2 messages:
          - adore_ros2_msgs: generated/ros2_messages/adore_ros2_msgs/README.md

      - Tools:
          - ADORe API tools: generated/tools/adore_api/README.md
          - ROS 2 observer: generated/tools/ros2_observer/README.md

      - Testing:
          - ADORe model checker: generated/testing/adore_model_checker/README.md



  - Using ADORe:
      - ADORe CLI: technical_reference_manual/system_and_development/adore_cli.md
      - Scenario generation: technical_reference_manual/system_and_development/scenario_generation.md
      - Model checking with ADORe Mission Control: technical_reference_manual/system_and_development/model_checking_with_the_adore_mission_control.md
      - Problems and solutions: technical_reference_manual/problems_and_solutions.md

  - Development guide:
      - Development overview: technical_reference_manual/system_and_development/system_and_development.md
      - Anonymous cloning: technical_reference_manual/system_and_development/anonymous_cloning.md
      - Creating a new node: technical_reference_manual/system_and_development/creating_a_new_node.md
      - ROS unit testing: technical_reference_manual/system_and_development/ros_unit_testing.md
      - C++ library testing: technical_reference_manual/system_and_development/library_testing.md
      - System tests: technical_reference_manual/system_and_development/system_tests.md
      - Multi-arch support: technical_reference_manual/system_and_development/multiarch_support.md
      - Documentation system: technical_reference_manual/system_and_development/documentation_generation_system.md
      - Doxygen documentation: technical_reference_manual/system_and_development/doxygen_documentation.md
      - Documentation overview: technical_reference_manual/system_and_development/documentation.md
      - Docs style guide: technical_reference_manual/styleguide.md

  - Licensing & legal:
      - Licensing overview: technical_reference_manual/licensing.md
      - Software license: technical_reference_manual/software_license.md
      - License check: technical_reference_manual/licensing/license_check.md
      - License header templates:
          - Template (Markdown): technical_reference_manual/licensing/license_header_template.md
          - Template (C header): technical_reference_manual/licensing/license_header_template.h
          - Template (Text): technical_reference_manual/licensing/license_header_template.txt
          - Template (XML): technical_reference_manual/licensing/license_header_template.xml



extra:
  github_issues: "https://github.com/eclipse-adore/adore/issues"

theme:
  name: material
  logo: img/adore_logo_white.png
  favicon: img/DLR_Logo.svg
  font:
    text: Atkinson Hyperlegible Next
    code: Anonymous Pro

  # Light/dark toggle with subtle colours (tweak as you like)
  palette:
    - scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - navigation.tabs
    - toc.integrate
    - content.code.copy
    - content.tabs.link

# Nice markdown extras powered by pymdown-extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - redirects
