# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ros_bridge.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ros_bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ros_bridge.proto\x12\nros_bridge\"m\n\nRosMessage\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x10\n\x08ros_type\x18\x02 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x12\x0b\n\x03seq\x18\x05 \x01(\x03\x12\x10\n\x08stamp_ns\x18\x06 \x01(\x03\"C\n\x10SubscribeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x10\n\x08ros_type\x18\x02 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\"\"\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x86\x01\n\tRosBridge\x12\x34\n\x07Publish\x12\x16.ros_bridge.RosMessage\x1a\x0f.ros_bridge.Ack(\x01\x12\x43\n\tSubscribe\x12\x1c.ros_bridge.SubscribeRequest\x1a\x16.ros_bridge.RosMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ros_bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROSMESSAGE']._serialized_start=32
  _globals['_ROSMESSAGE']._serialized_end=141
  _globals['_SUBSCRIBEREQUEST']._serialized_start=143
  _globals['_SUBSCRIBEREQUEST']._serialized_end=210
  _globals['_ACK']._serialized_start=212
  _globals['_ACK']._serialized_end=246
  _globals['_ROSBRIDGE']._serialized_start=249
  _globals['_ROSBRIDGE']._serialized_end=383
# @@protoc_insertion_point(module_scope)
