name: Release ADORe

inputs:
  archive_name:
    description: 'Name of the uploaded build archive'
    required: true

runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
        path: clean_repo

    - name: Download build archive
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.archive_name }}

    - name: Unpack build archive
      shell: bash
      run: |
        tar --extract --preserve-permissions --file=adore_${{ inputs.archive_name }}.txz --directory=build

    - name: List release contents
      shell: bash
      run: |
        ls -lah
        ls -lah build
        ls -lah clean_repo

    - name: Get clean branch name
      shell: bash
      # From https://github.com/DLR-TS/make_gadgets/blob/master/tools/branch_name.sh
      run: echo "BUILD_BRANCH=$(echo ${{ github.ref_name }} | tr -d '[:space:]' | tr -s -c "[:alnum:][:blank:]\.\_\-" _ | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Create release archive
      shell: bash
      run: |
        tar --create --auto-compress --preserve-permissions --file=adore_${BUILD_BRANCH}_latest_${{ inputs.archive_name }}.txz \
          build/* \
          clean_repo/adore_scenarios \
          clean_repo/tools/adore_api \
          clean_repo/tools/lichtblick \
          clean_repo/setup.sh \
          clean_repo/README.md \
          clean_repo/NOTICE.md \
          clean_repo/LICENSE

    - name: List package
      shell: bash
      run: |
        ls -lah
