name: Release ADORe

inputs:
  archive_name:
    description: 'Name of the uploaded build archive'
    required: true

runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
        path: clean_repo
        submodules: 'recursive'

    - name: Download build archive
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.archive_name }}

    - name: List downloads
      shell: bash
      run: |
        ls -lah

    - name: Unpack build archive
      shell: bash
      run: |
        mkdir -p build
        tar --extract --preserve-permissions --file=adore_${{ inputs.archive_name }}.txz --directory=build

    - name: List release contents
      shell: bash
      run: |
        ls -lah
        ls -lah build
        ls -lah clean_repo

    - name: Get clean branch name
      shell: bash
      # From https://github.com/DLR-TS/make_gadgets/blob/master/tools/branch_name.sh
      run: echo "BUILD_BRANCH=$(echo ${{ github.ref_name }} | tr -d '[:space:]' | tr -s -c "[:alnum:][:blank:]\.\_\-" _ | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Create release archive
      shell: bash
      run: |
        tar --create --preserve-permissions --file=adore_latest.tar --directory build .
        tar --append --preserve-permissions --file=adore_latest.tar --directory clean_repo \
          adore_scenarios \
          tools/adore_api \
          setup.sh \
          README.md \
          NOTICE.md \
          LICENSE
        xz --to-stdout adore_latest.tar > adore_${BUILD_BRANCH}_latest_${{ inputs.archive_name }}.txz

    - name: List package
      shell: bash
      run: |
        ls -lah
