message("target_functions.cmake loaded")

include(CMakePackageConfigHelpers)

function(get_targets targets)
    set(${result} "")
    get_property(targets GLOBAL PROPERTY GLOBAL_TARGETS)
    foreach(target ${targets})
        get_target_property(target_type ${target} TYPE)
        if(NOT target_type STREQUAL "EXECUTABLE")
            list(APPEND ${result} ${target})
        endif()
    endforeach()
    set(${targets} ${result} PARENT_SCOPE)
endfunction()

function(get_all_targets result)
endfunction()

function(is_library PATH RETURN_VALUE)
    if(EXISTS "${PATH}/include" AND EXISTS "${PATH}/src")
        set(${RETURN_VALUE} TRUE PARENT_SCOPE)
    else()
        set(${RETURN_VALUE} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(is_interface PATH RETURN_VALUE)
    if(EXISTS "${PATH}/include" AND NOT EXISTS "${PATH}/src")
        set(${RETURN_VALUE} TRUE PARENT_SCOPE)
    else()
        set(${RETURN_VALUE} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(is_executable TARGET_NAME RETURN_VALUE)
    get_target_property(target_type ${TARGET_NAME} TYPE)
    if(target_type STREQUAL "EXECUTABLE")
        set(RETURN_VALUE TRUE PARENT_SCOPE)
    else()
        set(RETURN_VALUE FALSE PARENT_SCOPE)
    endif()
endfunction()

function(check_link_library src_target dest_target result)
    get_target_property(dest_target_libraries ${dest_target} LINK_LIBRARIES)
    if(dest_target_libraries)
        list(FIND dest_target_libraries ${src_target} index)
        if(index EQUAL -1)
            set(${result} FALSE PARENT_SCOPE)
        else()
            set(${result} TRUE PARENT_SCOPE)
        endif()
    else()
        set(${result} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(find_all_requirements search_dir)
    if(NOT EXISTS "${search_dir}")
        return()
    endif()
    file(GLOB_RECURSE requirements_files "${search_dir}/*/requirements.cmake")
    foreach(req_file ${requirements_files})
        get_filename_component(req_dir ${req_file} DIRECTORY)
        get_filename_component(lib_name ${req_dir} NAME)
        include(${req_file})
    endforeach()
endfunction()

function(get_cmake_packages result)
    set(packages "")
    get_cmake_property(all_vars VARIABLES)
    foreach(var_name ${all_vars})
        if(var_name MATCHES "^([A-Za-z0-9_]+)_FOUND$")
            string(REGEX REPLACE "^([A-Za-z0-9_]+)_FOUND$" "\\1" package_name "${var_name}")
            if(${var_name})
                list(APPEND packages ${package_name})
            endif()
        endif()
    endforeach()
    set(${result} ${packages} PARENT_SCOPE)
endfunction()

function(get_package_targets packages result)
    set(all_targets "")
    foreach(package ${packages})
        if(DEFINED ${package}_TARGETS)
            list(APPEND all_targets ${${package}_TARGETS})
        endif()
    endforeach()
    set(${result} ${all_targets} PARENT_SCOPE)
endfunction()

macro(generate_library_targets SOURCE_DIRECTORY)
    message("")
    message("Generating CMake library targets...")
    set(cmakeignore_file "${CMAKE_SOURCE_DIR}/.cmakeignore")
    message("  Using .cmakeignore: ${cmakeignore_file}")

    file(GLOB directories CONFIGURE_DEPENDS "${SOURCE_DIRECTORY}/*")

    foreach(directory ${directories})
        is_library(${directory} is_library_return_value)
        is_interface(${directory} is_interface_return_value)
        
        if(is_library_return_value OR is_interface_return_value)
            set(ignore_path FALSE)
            cmakeignore(${directory} ${cmakeignore_file} RETURN_VALUE)
            set(ignore_path ${RETURN_VALUE})
            
            if(NOT ignore_path)
                if(IS_DIRECTORY ${directory})
                    get_filename_component(library_name ${directory} NAME)
                    message("  Generating library target: ${library_name}")
                    message("    directory: ${directory}")

                    if(is_library_return_value)
                        add_library(${library_name} STATIC)
                        file(GLOB_RECURSE library_sources "${directory}/*.cpp")
                        target_sources(${library_name} PRIVATE ${library_sources})
                        
                        # Add PRIVATE include directory so the library can find its own headers
                        target_include_directories(${library_name} PRIVATE "${directory}/include")
                        
                        # Set C++20 and PIC for compatibility
                        target_compile_features(${library_name} PUBLIC cxx_std_20)
                        set_target_properties(${library_name} PROPERTIES POSITION_INDEPENDENT_CODE ON)
                    else()
                        add_library(${library_name} INTERFACE)
                        target_compile_features(${library_name} INTERFACE cxx_std_20)
                    endif()
                    
                    target_include_directories( ${library_name} INTERFACE 
                        $<BUILD_INTERFACE:${directory}/include>
                        $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
                        )

                    set(requirements_file "${directory}/requirements.cmake")
                    if(EXISTS "${requirements_file}")
                        message("    Including requirements: ${requirements_file}")
                        include("${requirements_file}")
                    endif()

                    set_target_properties(${library_name} PROPERTIES
                        ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib"
                        )

                    set_target_properties(${library_name} PROPERTIES
                        OUTPUT_NAME "${library_name}"
                        )

                    if(EXISTS "${directory}/include")
                        file(COPY "${directory}/include" DESTINATION "${CMAKE_BINARY_DIR}/lib/${library_name}")
                    endif()

                    if(EXISTS "${CMAKE_SOURCE_DIR}/cmake/InstallTargets.cmake")
                        include(${CMAKE_SOURCE_DIR}/cmake/InstallTargets.cmake)
                    endif()
                endif()
            else()
                message("  The directory: ${directory}") 
                message("  is in the .cmakeignore file, skipping creation of target")
                message("  remove this pattern from the .cmakeignore file to auto-generate the target.")
                message("")
            endif()
        else()
            message("  The directory: ${directory} is not a library.")
            message("    Skipping auto-target creation.")
            message("    Add an `include` and `source` directory to:${directory} to auto-generate a target for this directory.")
            message("")
        endif()
    endforeach()

    get_property(targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
    foreach(target ${targets})
        add_all_target_include_directories(${target})
        add_all_target_link_libraries(${target})
    endforeach()
endmacro()

macro(add_all_target_include_directories NEW_TARGET)
    get_target_property(NEW_TARGET_TYPE ${NEW_TARGET} TYPE)
    
    get_property(targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
    foreach(target ${targets})
        get_target_property(target_type ${target} TYPE)
        
        if(NEW_TARGET STREQUAL target)
            continue()
        endif()
        if(target_type STREQUAL "UTILITY")
            continue()
        endif()
        if(NEW_TARGET_TYPE STREQUAL "UTILITY")
            continue()
        endif()
        if(NEW_TARGET_TYPE STREQUAL "STATIC_LIBRARY")
            continue()
        endif()
        if(NEW_TARGET_TYPE STREQUAL "INTERFACE_LIBRARY")
            continue()
        endif()

        # Check if include directory exists
        set(include_dir "${CMAKE_SOURCE_DIR}/lib/${target}/include")
        if(EXISTS "${include_dir}")
            message("    Adding target include directories for target: '${NEW_TARGET}' of type: ${NEW_TARGET_TYPE} from target: ${target} of type: ${target_type}")
            target_include_directories(${NEW_TARGET} PRIVATE "${include_dir}")
        endif()
    endforeach()
endmacro()

macro(add_all_target_link_libraries NEW_TARGET)
    find_all_requirements("${CMAKE_SOURCE_DIR}/lib")

    get_property(targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
    foreach(target ${targets})
        get_target_property(NEW_TARGET_TYPE ${NEW_TARGET} TYPE)
        get_target_property(target_type ${target} TYPE)
        
        if(target_type STREQUAL "EXECUTABLE")
            continue()
        endif()
        if(NEW_TARGET_TYPE STREQUAL "UTILITY" OR target_type STREQUAL "UTILITY")
            continue()
        endif()
        if(${NEW_TARGET} STREQUAL ${target})
            continue()
        endif()

        check_link_library(${target} ${NEW_TARGET} already_linked)
        if(already_linked)
            continue()
        endif()

        if(NEW_TARGET_TYPE STREQUAL "INTERFACE_LIBRARY")
            target_link_libraries(${NEW_TARGET} INTERFACE "${target}")
        else()
            target_link_libraries(${NEW_TARGET} PRIVATE "${target}")
        endif()
    endforeach()

    get_cmake_packages(PACKAGES)
    foreach(package ${PACKAGES}) 
        get_package_targets(${PACKAGES} RETURN_VALUE)
        set(package_targets ${RETURN_VALUE})
        foreach(package_target ${${package}_TARGETS})
            get_target_property(target_type ${NEW_TARGET} TYPE)
            if(target_type STREQUAL "INTERFACE_LIBRARY")
                target_link_libraries(${NEW_TARGET} INTERFACE "${package_target}")
            elseif(target_type STREQUAL "UTILITY")
                continue()
            else()
                target_link_libraries(${NEW_TARGET} PRIVATE "${package_target}")
            endif()
        endforeach()
    endforeach()
endmacro()

macro(link_package_targets PACKAGE TARGET)
    find_package(${PACKAGE} REQUIRED)
    get_property(${PACKAGE}_IMPORTED_TARGETS GLOBAL PROPERTY IMPORTED_TARGETS)
    foreach(package_target ${${PACKAGE}_IMPORTED_TARGETS})
        target_link_libraries(${TARGET} PRIVATE ${package_target})
    endforeach()
endmacro()

macro(generate_executable_targets folder)
    execute_process(
        COMMAND grep -rlPz --include=*.cpp "int\\s+main\\s*\\(" ${folder}
        RESULT_VARIABLE grep_result
        OUTPUT_VARIABLE grep_output
        )

    if(grep_result EQUAL 0)
        string(REGEX REPLACE "\n" ";" source_files_with_main ${grep_output})

        find_all_packages("${CMAKE_SOURCE_DIR}/build/share")
        find_all_packages("${CMAKE_SOURCE_DIR}/../vendor/mathematics_toolbox/eigen/build")

        set(cmakeignore_file "${CMAKE_SOURCE_DIR}/.cmakeignore")
        message("")
        message("Generating CMake executable targets...")
        message("  Using .cmakeignore: ${cmakeignore_file}")
        message("")
        foreach(source_file ${source_files_with_main})

            message("")
            set(ignore_path FALSE)
            cmakeignore(${source_file} ${cmakeignore_file} RETURN_VALUE)
            set(ignore_path ${RETURN_VALUE})
            if(NOT ignore_path)

                get_filename_component(file_name ${source_file} NAME_WE)
                set(executable_target "${file_name}")
                message("  Generating executable target: ${executable_target}")
                add_executable(${executable_target} ${source_file})

                add_all_target_include_directories(${executable_target})
                add_all_target_link_libraries(${executable_target})

                get_property(targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
                foreach(target ${targets})
                    get_target_property(target_type ${target} TYPE)
                    if(NOT "${target_type}" MATCHES "EXECUTABLE")
                        # Additional linking logic can go here
                    endif()
                endforeach()

                get_cmake_property(variables VARIABLES)
                foreach(variable ${variables})
                    if(variable MATCHES "_headers_DIR$")
                        # Additional header logic can go here
                    endif()
                endforeach()

                set_target_properties(${file_name} PROPERTIES
                    RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin
                    )

            else()
                message("  The source file: ${source_file}") 
                message("  is in the .cmakeignore file, skipping creating executable.")
                message("  remove this pattern from the .cmakeignore file to auto-generate the target.")
                message("")
            endif()
        endforeach()
    else()
        message(STATUS "  No files with 'int main(' found in ${folder}. No executable targets to generate.")
    endif()
endmacro()

function(print_libraries)
    message(STATUS "Defined libraries/packages in the project:")
    get_property(package_list GLOBAL PROPERTY PACKAGES)
    foreach(package ${package_list})
        message(STATUS " - ${package}")
    endforeach()
endfunction()

function(find_all_packages CMAKE_SHARE_DIR)
    if(NOT EXISTS "${CMAKE_SHARE_DIR}")
        return()
    endif()
    
    list(APPEND CMAKE_PREFIX_PATH "${CMAKE_SHARE_DIR}")
    file(GLOB package_subdirs "${CMAKE_SHARE_DIR}/lib/*")
    foreach(package_dir ${package_subdirs})
        if(IS_DIRECTORY ${package_dir})
            get_filename_component(package_name ${package_dir} NAME)
            find_package(${package_name} QUIET)

            if(${package_name}_FOUND)
                get_cmake_property(_vars VARIABLES)
                foreach(_var ${_vars})
                    if(_var MATCHES "^${package_name}_.*")
                        set(${_var} ${${_var}} PARENT_SCOPE)
                    endif()
                endforeach()
                message(STATUS "Found package: ${package_name}")
            else()
                message(STATUS "Package ${package_name} not found.")
            endif()
        endif()
    endforeach()
endfunction()
