---
name: ADORe CI

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:


jobs:
  build_native_x86:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Build
        uses: "./.github/templates/build"
        with:
          archive_name: "build_x86"

  release_native_x86:
    runs-on: ubuntu-24.04
    needs: build_native_x86

    permissions:
      contents: write
      actions: write
      attestations: write

    steps:
      - name: Prepare Release
        uses: "./.github/templates/release"
        with:
          archive_name: "build_x86"
    
      - name: Release
        uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          files: |
            adore_*_latest_build_x86.txz

  build_native_arm64:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Build
        uses: "./.github/templates/build"
        with:
          archive_name: "build_arm64"

      - name: Upload build archive
        uses: actions/upload-artifact@v4
        with:
          name: build_arm64
          path: |
             adore_*_latest_build_arm64.txz
      

  release_native_arm64:
    runs-on: ubuntu-24.04
    needs: build_native_arm64

    permissions:
      contents: write
      actions: write
      attestations: write

    steps:
      - name: Prepare Release
        uses: "./.github/templates/release"
        with:
          archive_name: "build_arm64"
    
      - name: Release
        uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          files: |
            adore_*_latest_build_arm64.txz
