name: ADORe CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  x86_64:
    name: Native x86_64
    if: startsWith(github.repository, 'eclipse-adore/')
    permissions:
      contents: read
      packages: write
    secrets: inherit
    uses: ./.github/workflows/reuse-build.yaml
    with:
      platform: 'ubuntu-24.04'
      arch: 'x86_64'

  arm64:
    name: Native arm64
    if: startsWith(github.repository, 'eclipse-adore/')
    permissions:
      contents: read
      packages: write
    secrets: inherit
    uses: ./.github/workflows/reuse-build.yaml
    with:
      platform: 'ubuntu-24.04-arm'
      arch: 'arm64'
