---
name: CI_native_x86

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:


jobs:
  build_native_x86:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          
      - name: build
        uses: "./.github/templates/build.yaml"

  release:
    needs: build_native_x86
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write
      attestations: write

    steps:
      - name: Download build archive
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Create release archive
        run: |
          tar -caf adore_${{ github.ref_name }}_latest_x86.txz *

      - name: Release
        uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          files: |
            adore_${{ github.ref_name }}_latest_x86.txz
